### ISSUE TITLE
Question: Default login credentials

### ISSUE THREAD

**Issue by mountainclimbing** [dhis2/dhis2-android-skeleton-app#84]
Hello,

Am trying out this app. Do we have default for:

server url:
Username:
Password: 

Are the checks dependant on one url or the url can be changed as required? any changes that need to be made?

**Comment by vgarciabnz** [comment]
Hi @mountainclimbing,

you can use any demo server using the default user admin:district or the android specific user android:Android123. Demo servers are listed here https://play.dhis2.org/.

In the the skeleton app you can change the url and user credentials at login to use your own instance.

Hope this helps

**Comment by mountainclimbing** [comment]
Hello,

Thank you for the feedback. Am very new to Native Android, am used with Cordova/Phonegap. 
I have been trying:
url: https://play.dhis2.org/
username: admin
Password: district

But I keep receiving "login failed"

"In the the skeleton app you can change the url and user credentials at login to use your own instance."
Is there any java file that I need to edit in the App to put the new URL? because on the front end app, I can login.

**Comment by vgarciabnz** [comment]
Hi,
in https://play.dhis2.org/ you can find the server list, but the actual server url is for example https://play.dhis2.org/2.34.0/ for demo 2.34.0.
The skeleton app has a login screen with three inputs: url, username and password. It is there where you can set the new url

**Comment by mountainclimbing** [comment]
Hello,
Thank you. It has worked.
One last question, do you also have demo DHIS 2 apps developed in Cordova?

**Comment by vgarciabnz** [comment]
I am sorry but we don't have a demo app developed in Cordova so far. It would be great to hear about your findings on that, so please feel free to share anything about it either in github or in dhis2 [community](https://community.dhis2.org/c/development/sdk-android-development)

**Comment by mountainclimbing** [comment]
Thank you for your support.
